---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# setc

<!-- badges: start -->
<!-- badges: end -->

[setc](https://github.com/bvkrauth/setc) is an [R](https://www.r-project.org/) package for extracting results from the course-level reports generated by
Simon Fraser University's Student Evaluation of Teaching and Courses system.  

Course-level SETC reports can be downloaded at https://sfu.bluera.com/SFU
(login required).
Instructors have access to their own reports, supervisors such as chairs
have access to all reports from their units.  Reports are PDF
files with extensive formatting and graphics.  The SETC package extracts
the key results from these files and assembles them into CSV files that are suitable for analysis.

## Installation

In order to use this package, you need to:

 1. [Install R](https://www.r-project.org/) if you do not already have it.
 2. Open R and install the setc package:

``` r
install.packages("devtools")
library(devtools)
install_github("bvkrauth/setc")
```

 3. Access the help from within R to see how to use the package.

``` r
library(setc)
? setc
```

## For additional information

Please send questions and bug reports to bkrauth@sfu.ca.

