#' Combine a particular data set across multiple terms
#'
#' \code{combine_aross_terms} combines multiple terms of a SETC
#' data set generated by \code{get_setc_data()} into a single
#' pooled data set.
#'
#' @param data_structure A string describing an SETC data structure
#'        Possible values include "course" or "comments"
#'
#' @param data_folder The folder in which the data can be found
#'
#' @return A tibble (data frame) constructed by \code{rbind}ing
#' every CSV file in \code{data_folder} with a filename of the
#' form \code{data_structure_TERM.csv} where \code{TERM} is a valid term (e.g. "Fa16")
#' @export
#'
#' @examples
combine_across_terms <- function(data_structure, data_folder){
  file_names <- dir(data_folder,
                    pattern = stringr::str_c("(Fa|Sp|Su)[0-9]{2}_", data_structure, ".csv"),
                    full.names = TRUE)
  dat <- NULL
  if (length(file_names) > 0){
    for (i in 1:length(file_names)) {
      current_term <- readr::read_csv(file_names[i])
      dat <- rbind(dat, current_term)
    }
  }
  invisible(dat)
}
