#' Title
#'
#' @param question_file a file name
#' @param output_file a file name
#'
#' @return
#' @export
#'
#' @examples
get_questions <- function(question_file=NULL, output_file = NULL){
  if (is.null(question_file)) {
    question <- get_default_questions()
  } else {
    question <- readr::read_csv(question_file)
    question$score_legend <- stringr::str_c(question$label_1, question$label_2, question$label_3, question$label_4, question$label_5, sep = " | ")
  }
  if (!is.null(output_file)){
    question %>%
      readr::write_excel_csv(output_file)
  }
  question
}

get_default_questions <- function(){
  structure(list(question_id = c("ACTI", "APPR", "ASES", "ATND",
                                 "CONC", "CONN", "CRIT", "EASY", "ENVI", "EXPT", "GDCT", "MORE",
                                 "MTRL", "QUAL", "THME"), question_text = c("Course activities",
                                                                            "The course instructor was approachable when students asked for guidance",
                                                                              "The assessments in this course", "I attended class", "The course instructor explained course concepts clearly",
                                                                              "The different course parts/activities", "My experience in this course has encouraged me to think critically",
                                                                              "How easy was this course", "The course instructor created a respectful learning environment",
                                                                              "The course instructor made it clear what students were expected to learn",
                                                                              "The course instructor explained grading criteria clearly", "My experience in this course has motivated me to learn more about the subject",
                                                                              "Course materials", "Overall, the quality of my learning experience in this course was",
                                                                              "When explaining course concepts, the instructor connected the concepts to the major themes"
                                   ), question_level = c("SFU", "SFU", "SFU", "SFU", "SFU", "SFU",
                                                         "FASS", "SFU", "SFU", "FASS", "SFU", "FASS", "SFU", "SFU", "FASS"
                                   ), table_type = c("grouped", "grouped", "grouped", "separate",
                                                     "grouped", "grouped", "separate", "separate", "grouped", "separate",
                                                     "grouped", "separate", "grouped", "separate", "separate"), fass_mean = c(3.85,
                                                                                                                              4.31, 3.98, 4.5, 4.08, 4.16, 4, 2.75, 4.41, 4.14, 4.07, 3.66,
                                                                                                                              4.09, 3.92, 4.27), sfu_mean = c(3.92, 4.34, 3.98, 4.57, 4.07,
                                                                                                                                                              4.18, NA, 2.69, 4.41, NA, 4.08, NA, 4.04, 3.93, NA), label_1 = c("Strongly Disagree",
                                                                                                                                                                                                                               "Strongly Disagree", "Strongly Disagree", "Never", "Strongly Disagree",
                                                                                                                                                                                                                               "Strongly Disagree", "Strongly Disagree", "Very Hard", "Strongly Disagree",
                                                                                                                                                                                                                               "Strongly Disagree", "Strongly Disagree", "Strongly Disagree",
                                                                                                                                                                                                                               "Strongly Disagree", "Very Poor", "Strongly Disagree"), label_2 = c("Disagree",
                                                                                                                                                                                                                                                                                                   "Disagree", "Disagree", "Rarely", "Disagree", "Disagree", "Disagree",
                                                                                                                                                                                                                                                                                                   "Hard", "Disagree", "Disagree", "Disagree", "Disagree", "Disagree",
                                                                                                                                                                                                                                                                                                   "Poor", "Disagree"), label_3 = c("No Opinion", "No Opinion",
                                                                                                                                                                                                                                                                                                                                    "No Opinion", "About half of the time", "No Opinion", "No Opinion",
                                                                                                                                                                                                                                                                                                                                    "No Opinion", "Medium", "No Opinion", "No Opinion", "No Opinion",
                                                                                                                                                                                                                                                                                                                                    "No Opinion", "No Opinion", "Fair", "No Opinion"), label_4 = c("Agree",
                                                                                                                                                                                                                                                                                                                                                                                                   "Agree", "Agree", "Most of the time", "Agree", "Agree", "Agree",
                                                                                                                                                                                                                                                                                                                                                                                                   "Easy", "Agree", "Agree", "Agree", "Agree", "Agree", "Good",
                                                                                                                                                                                                                                                                                                                                                                                                   "Agree"), label_5 = c("Strongly Agree", "Strongly Agree", "Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                         "All of the time", "Strongly Agree", "Strongly Agree", "Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                         "Very Easy", "Strongly Agree", "Strongly Agree", "Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                         "Strongly Agree", "Strongly Agree", "Very Good", "Strongly Agree"
                                                                                                                                                                                                                                                                                                                                                                                                   ), question_note = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
                                                                                                                                                                                                                                                                                                                                                                                                                        NA, NA, NA, "Test note for questions", NA), score_legend = c("Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Never | Rarely | About half of the time | Most of the time | All of the time",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Very Hard | Hard | Medium | Easy | Very Easy", "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     "Very Poor | Poor | Fair | Good | Very Good", "Strongly Disagree | Disagree | No Opinion | Agree | Strongly Agree"
                                                                                                                                                                                                                                                                                                                                                                                                                        )), row.names = c(NA, -15L), class = c("tbl_df", "tbl", "data.frame"
                                                                                                                                                                                                                                                                                                                                                                                                                        ))


}
