#' Extract comments from an SETC report
#'
#' \code{get_comments} extracts the comments from the text of
#' an SETC report.
#'
#' \code{get_comments} will look in \code{report_text} for the text
#' "Do you have any further comments?"  It will then treat (almost)
#' every line after that as a comment.
#'
#' If \code{report_text} does not include the text
#' "Do you have any further comments?", \code{get_comments}
#' will return NULL.
#'
#' @param report_text A vector of strings, usually
#' generated by \code{\link{get_report_text}}
#'
#' @param course_id a string that will be included as the course_id
#'
#' @return A tibble in which each row corresponds to a single
#' line of commentary, and the variables include the comment text
#' and the provided \code{course_id}.
#'
#' @export
#'
#' @examples
get_comments <- function(report_text, course_id = ""){
  comments <- NULL
  comment_appearance <- stringr::str_which(report_text,
                                           "Do you have any further comments?")
  if (length(comment_appearance) > 0) {
    comment_start <- comment_appearance[1] + 2
    if (comment_start <= length(report_text)) {
      tmptext <- report_text[comment_start:length(report_text)]
      tmptext <- tmptext[stringr::str_detect(tmptext, "^\\s")]
      tmptext <- stringr::str_replace(tmptext, "^\\s+", "")
      tmptext <- tmptext[tmptext != "Comments"]
      if (length(tmptext) > 0) {
        comments <- tibble::tibble(course_id = course_id,
                                   comment_number = seq_along(tmptext),
                                   comment_text = tmptext)
      }
    }
  }
  comments
}
